version: '3.8'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: telegram-bot:latest
    container_name: telegram-bot
    env_file:
      - .env
    volumes:
      - ./ip_cam.txt:/app/ip_cam.txt:ro
    restart: unless-stopped
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge